### ISSUE TITLE
love2d 0.10.0 required

### ISSUE THREAD

**Issue by GRiMe2D** [leafi/love-eclipse-ldt#1]
Love2D released 0.10.0
Please update

**Comment by leafi** [comment]
Aye, I'll look into it today or tomorrow.

**Comment by sirskunkalot** [comment]
I made a version for the current master of love-api. Do you want it, or have you built one by yourself by now?

**Comment by leafi** [comment]
I want it very badly indeed. I've just started a new job & my spare time project isn't LOVE-related, so I've been out of the LOVE2D space for a while now. (Sorry @GRIM2D.) I'll be back eventually, but your work looks great, and thank you very much for submitting it!

I'm going to adopt your stuff as-is. It looks wonderful.

(If you want the 'official' repo to be transferred to you then ask and I will give. Provided you'd be willing to transfer ownership back if you become busy and I become unbusy! Would love2d-community be willing to take ownership?)

Notes:
1. Change to top of main.lua says 0.10.0, whereas I swear somewhere else you wrote 0.10.1
2. There's a few comments near the top of main.lua of mine that still reference rmcode & begs you to use 0.9.2d. Please update/delete these.
3. Is everything in patch.lua still necessary with the current API definitions?
4. Something else I've completely forgotten.

**Comment by leafi** [comment]
Release built and everything merged. Does the .zip release work?

Edit: Also given you push access, @sirskunkalot , in case you find it's needed.

**Comment by sirskunkalot** [comment]
Hi leafi,

glad I could help. I just recently started learning Lua by programming a LÖVE application, so I needed this. I am not sure if I can maintain this the long term. I think with the release now we will be good until 0.11 or whatever comes next. I keep watching this repo, though. If something went horribly wrong here, I am sure I can spare some time to fix it ;) I cannot speak for love2d-community, but this sounds like a decent idea. As the 'official' owner, would you try to contact them? And yes: the .zip works as it is. 

Now to your 'Notes'
1. Will fix
2. Will fix
3. Did not check, to be honest. I did now and the only patch still needed is the patch of ultimate sorrow (had a good laugh :)) So: Will fix - I still did not check, if new patches are required.
4. Sorry, can't fix ;)

I had some ideas for this, too, which I filed under "COULDDO". Like testing, if global.lua from ./builtins contains the love module, in case somebody replaces this before building (which I did, just for the case that api.zip for Lua 5.1 changed in LDT - resulting in an one hour bug search). So maybe there are coming some more changes. If it is OK with you, I would push them to here directly?!

**Comment by leafi** [comment]
... think I'm a bit late on this one, but absolutely, sure, you can push them here directly :P

Whatever you need from me to make your life easier, you can have. Seriously thanks for keeping this updated & all your work I'm sure I've failed to acknowledge over the months. :)
