### ISSUE TITLE
How to run or debug current project?

### ISSUE THREAD

**Issue by ghost** [leafi/love-eclipse-ldt#5]
Don't understand, how I should setup run configurations to run main.lua with love.

![](http://i.imgur.com/W7Zpeln.png)

With this settings I can only run love, but don't know, how to specify the path to the project

**Comment by sirskunkalot** [comment]
Hi Winterwolf,

sorry for the late answer, I get kind of spammed with notifications lately. I won't offer eclipse support here, though. IIRC, you have to edit your run configuration for your particular project and set the path to your project folder as a parameter to the love-engine. For more help regarding eclipse setup check out the eclipse Wiki at https://wiki.eclipse.org/LDT.
