### ISSUE TITLE
Issue with Lua Love and Eclipse Luna

### ISSUE THREAD

**Issue by AlexandreMeslin** [leafi/love-eclipse-ldt#6]
Hi,

I just follow the instruction (pre-built version) on your page at Github. I downloaded the ZIP file and add as a new environment configuration. When I try to run the example, I got the following error: 

`
Exception in thread "main" com.naef.jnlua.LuaRuntimeException: ...rive/workspace-desktop-ubuntu/Lua Alo Mundo/main.lua:8: attempt to index global 'love' (a nil value)
	at com.naef.jnlua.LuaState.lua_pcall(Native Method)
	at com.naef.jnlua.LuaState.call(LuaState.java:555)
	at org.eclipse.ldt.support.lua51.internal.interpreter.JNLua51Launcher.run(JNLua51Launcher.java:128)
	at org.eclipse.ldt.support.lua51.internal.interpreter.JNLua51Launcher.main(JNLua51Launcher.java:143)
`

The example is (I tried to code the example use the code tag, but something wrong happening - sorry):

`
-- This is the main entry point of your LOVE2D game.
-- Feel free to delete the callbacks you don't need,
-- and visit https://www.love2d.org/wiki/love if you need more.

-- for rectangle example
local x, y, w, h = 20, 20, 60, 20

function love.load()
end

function love.draw()
  -- Draw a coloured rectangle.
  love.graphics.setColor(0, 100, 100);
  love.graphics.rectangle('fill', x, y, w, h);
end

function love.update(dt)
  -- Grow the rectangle.
  w = w + 1
  h = h + 1
end

function love.keypressed(key, isrepeat)
end

function love.keyreleased(key)
end

function love.textinput(text)
end

function love.mousepressed(x, y, button)
end

function love.mousemoved(x, y, dx, dy)
end

function love.mousereleased(x, y, button)
end
`

Can you help me, please!

Thanks in advanced.
Alexandre

**Comment by sirskunkalot** [comment]
Hi meslin8752,

maybe I am just a little too late on this... sorry. But: I don't want to close this unanswered ;)

&This looks like it is not a problem with love-eclipse-ldt but your chosen runtime. Only installing love-eclipse-ldt on a fresh install of eclipse LDT does not enable you to run löve code. You still need to install the löve runtime on your PC and enable it in eclipse LDT. This project only provides the Execution Environment for the löve runtime (see the LDT wiki pages: https://wiki.eclipse.org/LDT/User_Area/User_Guides/User_Guide_1.3#Execution_Environment for more information about an EE). If you need help setting up löve, the wiki at https://wiki.eclipse.org/LDT is a good start.
