### ISSUE TITLE
How to Run a Love project from Eclipse?

### ISSUE THREAD

**Issue by sergiofenoll** [leafi/love-eclipse-ldt#8]
How do I run the Love project from Eclipse itself? If I were to run it from the terminal I'd have to run `love .` inside the root directory of the project, how is this done in Eclipse?

Thanks!

**Comment by sirskunkalot** [comment]
Sorry, I won't offer eclipse support here. For more help regarding eclipse setup check out the eclipse Wiki at https://wiki.eclipse.org/LDT.
